"""add photo_path to posts table

Revision ID: 2b7d2cecf2ee
Revises: 551c3ba72f5f
Create Date: 2018-11-26 19:10:08.674012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7d2cecf2ee'
down_revision = '551c3ba72f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photo_path')
    # ### end Alembic commands ###
